management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    default:

  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

        #        - SaveSession
        #        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedToken: 1
        - name: Retry
          args:
            retries: 3
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fallback

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
        - id: rule-service
          uri: lb://rule-service
          predicates:
            - Path=/api/rule/**

        - id: baeker-member
          uri: lb://baeker-member
          predicates:
            - Path=/api/member/**

        - id: baeker-study
          uri: lb://baeker-study
          predicates:
            - Path=/api/studyrule/**,/api/study/**,/api/my-study/**

        - id: solved
          uri: lb://solved
          predicates:
            - Path=/api/solved/**

server:
  port: 9000


eureka:
  instance:
    preferIpAddress: true
    instance-id: ${custom.server}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${custom.server}:8761/eureka/a

custom:
  server: localhost

jasypt:
  encryptor:
    password:
    bean: jasyptStringEncryptor

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        sliding-window-size: 10  # 서킷브레이커가 마지막 10개 요청을 고려
        permitted-number-of-calls-in-half-open-state: 5 # 반절
        failure-rate-threshold: 50 # 그중 50%가 실패하면 open
        wait-duration-in-open-state: 10000 # 10초동안 open
        register-health-indicator: true
  timelimiter:
    instances:
      myCircuitBreaker:
        timeout-duration: 3s # 요청 시간 제한